Alert_workflow:

name: alertforpush

on:
  push:
    branches:
      - test

jobs:
  alerting:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git_branch=${GITHUB_REF#refs/heads/}
          echo "$git_branch"
          url=${GITHUB_API_URL}
          echo "$url"
