name: Triggering pipeline
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - run: |
        git_branch=${GITHUB_REF#refs/heads/}
        echo "$git_branch"
        commit_url="${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
        echo "$commit_url"
        
