name: alertforpush

on:
  push:
    branches:
      - test

jobs:
  alerting:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git_branch="${GITHUB_REF_NAME}"
          echo "$git_branch"
          url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
          echo "$url"
          curl -X POST -H 'Content-type: application/json' --data '{"text": "Push_merge_request","attachments": [{"fallback": "1","title": "User","text": "'"${GITHUB_ACTOR}"'"},{"fallback": "2","title": "Push_URL","text": "'"${url}"'"}]}' https://hooks.slack.com/services/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 https://hooks.slack.com/services/${{secrets.SLACK_TOKEN}}
