name: alertforpush

on:
  push:
    branches:
      - test

jobs:
  alerting:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git_branch="${GITHUB_REF_NAME}"
          echo "$git_branch"
          url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
          echo "$url"
          curl -X POST -H "Content-Type: application/json" -d '{"text":"'"${GITHUB_ACTOR}"'","text": "'"$url"'"}' https://hooks.slack.com/services/${{secrets.SLACK_TOKEN}}
