name: Django                                  # workflow name

on:
  push:                                       
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  build:
    runs-on: ubuntu-latest                    # similar to "image" in GitLab
    steps:
    - name: 'echoing'
    - run: echo "This is a build step" > my-artifact
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: my_file.txt
      

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a test step"

  integration:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is an integration step"
      - run: exit 1

  prod:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a deploy step"
