name: Learning workflow

on:
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - run: |
         echo "this is test step"
         pwd
         ls >> 1.txt
         cat 1.txt
         whoami
