name: Learning workflow
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - run: |
         echo "this is test step"
         ls >> 1.txt
         cat 1.txt
         whoami
         shell: /usr/bin/bash -e {0}
